#!/bin/bash

# Requirement : awscli
command -v aws >/dev/null 2>&1 || { echo "We require awscli but it's noti installed.  Aborting." >&2; exit 1; }

[ -z "$1" ] && { echo "Please specify the security group id"; exit 1; }
[ -z "$2" ] && { echo "Please specify the subnet id"; exit 1; }
[ -z "$3" ] && { echo "Please specify the number of instances to run"; exit 1; }
[ -z "$4" ] && { echo "Please specify the cluster name"; exit 1; }

# Run the instances needed
aws ec2 run-instances --image-id ami-8ca83fec --count $3 --instance-type t2.micro --security-group-ids $1 --subnet-id $2 --associate-public-ip-address

# Create the cluster
aws ecs create-cluster --cluster-name $4


